login: &login
  adapter: postgresql
  host: localhost
  port: 5432
  username: joebuhlig
  password:

connection: &connection
  encoding: unicode
  pool: 5


development:
  database: publify_dev
  <<: *login
  <<: *connection

test:
  database: publify_tests
  <<: *login
  <<: *connection

production:
  database: publify
  <<: *login
  <<: *connection
